export const SET_USER = 'SET_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const USER_ONLINE = 'USER_ONLINE'
export const USER_OFFLINE = 'USER_OFFLINE'
export const RESET_USERS = 'RESET_USERS'

export const ASYNC_SET_FLAG = 'ASYNC_SET_FLAG'
export const ASYNC_START = 'ASYNC_START'
export const ASYNC_FINISH = 'ASYNC_FINISH'
export const ASYNC_ERROR = 'ASYNC_ERROR'
export const RESET_ASYNC = 'RESET_ASYNC'

export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

export const SET_CHANNEL = 'SET_CHANNEL'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const SET_CHANNELS = 'SET_CHANNELS'
export const CLEAR_CHANNEL = 'CLEAR_CHANNEL'
export const CLEAR_CHANNELS = 'CLEAR_CHANNELS'
export const RESET_CHANNELS = 'RESET_CHANNELS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
export const RESET_MESSAGES = 'RESET_MESSAGES'

export const UPDATE_UNSEEN_MSG_COUNT = 'UPDATE_UNSEEN_MSG_COUNT'
